Default: &defaults
  database: PetShop.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: PetShop_test.sqlite3
  <<: *defaults

Staging:
  database: PetShop_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: PetShop_production.sqlite3
  poolsize: 100
  <<: *defaults
